# Site settings
title: Abishek Akella
email: abishek.akella@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: 
url:  http://akakella.github.io
twitter_username: akakella
github_username:  akakella

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  projects:
    output: true
    permalink: /projects/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


